FROM amd64/python:3.7-slim-buster

WORKDIR /app

ADD ./0.bmp .
ADD ./1.bmp .
ADD ./2.bmp .
ADD ./3.bmp .
ADD ./4.bmp .
ADD ./5.bmp .
ADD ./6.bmp .
ADD ./7.bmp .
ADD ./8.bmp .
ADD ./9.bmp .
ADD ./10.bmp .
ADD ./11.bmp .
ADD ./12.bmp .

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]